project_id = "abrvlbkridfthygzbzln"

[functions.check-geofences]
verify_jwt = false

[functions.optimize-geofences]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-career-notification]
verify_jwt = false
